export const PersonnelData = [
    {
        "Id": "8f701429-4b58-4864-b83a-d02daa249441",
        "Code": "20000001",
        "Name": "مدیر سیستم",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 102,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "64a56131-1f44-4aac-b3ec-5a8be6d00c9d",
        "Code": "20000003",
        "Name": "جهانگرد رضایی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10200,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "4b0cdae4-2ec6-4334-b89d-b1e573d55f29",
        "Code": "20000004",
        "Name": "عبدل علی علوی پور",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 102,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "3db14216-8c2e-4bd0-8757-c7e8292b85e9",
        "Code": "20000005",
        "Name": "کامران رستمی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 102,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "d876b2d2-fcec-4ecd-9e86-2bf17f650bc1",
        "Code": "20000006",
        "Name": "سحر  سیاه کمری ",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 102,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "d606d682-1062-4b51-9f04-57af0a3dbb91",
        "Code": "20000007",
        "Name": "مغایرت مغایرت",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 102,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "ea8f4cc1-71f1-461c-b3e9-b6f33a35dca1",
        "Code": "20000008",
        "Name": "نسخه دمو",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 102,
        "PartnerAddress": "",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "271ff31d-ba18-4bc3-9fa2-0c8e81a404e9",
        "Code": "20000009",
        "Name": "تست تستی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 102,
        "PartnerAddress": "",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "82f6c9df-9a67-4394-90fe-2c631bef4682",
        "Code": "20200001",
        "Name": "احسان رضایی ",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10202,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "5a82e012-7ca3-4e62-a2bb-51422173fdf3",
        "Code": "20400001",
        "Name": "فروشنده اینترنتی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "d84f5c0b-4b2c-4c17-aa9e-d81237be69cc",
        "Code": "20400003",
        "Name": "وحید  چقازردی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "d77c0804-137e-4f33-9055-ad5aeb99dfeb",
        "Code": "20400004",
        "Name": "مجید  رنجبر",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "5d39e66a-42de-4279-9ea0-c4529bda084a",
        "Code": "20400006",
        "Name": "شادی بوجاری",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "24cec17b-7e7b-46a7-999f-db4e8de13268",
        "Code": "20400007",
        "Name": "ایرج علیپور",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "572fa35a-2a74-4a68-bd24-76d8ce472417",
        "Code": "20400008",
        "Name": "امیر  کلهری",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "12670ea8-4b63-4dcc-9f23-df00bbac638d",
        "Code": "20400009",
        "Name": "فاطمه محمدی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "e12447d2-db67-4ce5-906b-66a9cb742bb4",
        "Code": "20400010",
        "Name": "اسما رضایی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "956fa9bb-6bc8-4227-8724-3945c224cc89",
        "Code": "20400011",
        "Name": "مریم ریزوندی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "128027df-24fe-4359-9bb4-7b40938cb604",
        "Code": "20400012",
        "Name": "پوریا  جعفری",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "8d22716a-9e4d-4611-86ea-0d35ab527925",
        "Code": "20400013",
        "Name": "شهرام  رشیدی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "a4799889-a1fa-4251-b62a-920b873c5642",
        "Code": "20400014",
        "Name": "علیرضا سلطانی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "637a6686-9f0b-405f-a7f4-e70b809fdd32",
        "Code": "20400015",
        "Name": "سعید کرانیان",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "80d5d3fe-293b-4e41-8754-dbe02cf56086",
        "Code": "20400016",
        "Name": "عرفان صفایی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "2173976c-8397-42db-9813-99130fd7d4f7",
        "Code": "20400017",
        "Name": "پریا کرمی",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "b6f6bf1b-2b0e-46dd-b324-e3b9e8deedfc",
        "Code": "20400018",
        "Name": "سحر اصغری",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "2dabfb3e-04fd-4445-9cf8-37573be06dc5",
        "Code": "20400019",
        "Name": "فاطمه کمری",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "796751c2-4e72-40cd-a620-6aa3462f19d0",
        "Code": "20400020",
        "Name": "پیام سلیمی نیا",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "2d9d87df-0dd8-424d-b512-e75777338bb3",
        "Code": "20400021",
        "Name": "زهرا سهیلی راد",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "6436987a-376b-4ca9-8b3e-e44c84fab893",
        "Code": "20400022",
        "Name": "میثم شاهرخی راد",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    },
    {
        "Id": "3a4eb82b-f6c9-4e47-8bf8-f0e919adb12e",
        "Code": "20400023",
        "Name": "رضایی کامبیز",
        "PersonTelephone": "",
        "PersonLegalName": "",
        "DefaultPackageName": null,
        "DefaultPackageId": "00000000-0000-0000-0000-000000000000",
        "EntityGlobalType": 10204,
        "PartnerAddress": "تهران صادقیه",
        "StuffGroupCode": "",
        "StuffBasketIds": [],
        "Units": [],
        "VATPercent": 0,
        "SaleDefaultPackageId": null,
        "SaleDefaultPackageUnitId": "",
        "SaleDefaultPackageName": "",
        "SaleDefaultPackageCoefficient": 0,
        "BankAccountNumber": "",
        "StuffDescription": "",
        "MaxPackageCoefficient": 0,
        "ExpirationDateFormat": null,
        "EntityIsPerson": true
    }
]

export const RulesList=[
    {
        "Id": "2165f24f-fbc6-4067-8329-55b4113701fd",
        "Title": "حکم حقوق آقای جهانگیر سال 1401",
        "JobStartDate": "1401/01/01",
        "JobEndDate": "1401/12/29",
        "PaidLeaveSum_Day": 2,
        "PaidLeaveSum_Hour": 4,
        "PaidLeaveHourDayCoefficient": 6
    }
]


export const MonthlyHours=[
    {
        "Day": "چهارشنبه",
        "Date": "1401/04/01",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": true,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": true
    },
    {
        "Day": "پنجشنبه",
        "Date": "1401/04/02",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 8,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "جمعه",
        "Date": "1401/04/03",
        "DayStartTime": 0,
        "DayEndTime": 0,
        "StartTime": 9,
        "EndTime":12,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "شنبه",
        "Date": "1401/04/04",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 12,
        "StartTime2": 13,
        "EndTime2": 15,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "یکشنبه",
        "Date": "1401/04/05",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 9,
        "StartTime2": 13,
        "EndTime2": 16,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 9,
        "HourlyLeaveEndTime": 13,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "دوشنبه",
        "Date": "1401/04/06",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": true,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "سه شنبه",
        "Date": "1401/04/07",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": true,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "چهارشنبه",
        "Date": "1401/04/08",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "پنجشنبه",
        "Date": "1401/04/09",
        "DayStartTime": 0,
        "DayEndTime": 0,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "جمعه",
        "Date": "1401/04/10",
        "DayStartTime": 0,
        "DayEndTime": 0,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "شنبه",
        "Date": "1401/04/11",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": true
    },
    {
        "Day": "یکشنبه",
        "Date": "1401/04/12",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "دوشنبه",
        "Date": "1401/04/13",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": true,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "سه شنبه",
        "Date": "1401/04/14",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": true,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "چهارشنبه",
        "Date": "1401/04/15",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "پنجشنبه",
        "Date": "1401/04/16",
        "DayStartTime": 0,
        "DayEndTime": 0,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "جمعه",
        "Date": "1401/04/17",
        "DayStartTime": 0,
        "DayEndTime": 0,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "شنبه",
        "Date": "1401/04/18",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "یکشنبه",
        "Date": "1401/04/19",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "دوشنبه",
        "Date": "1401/04/20",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "سه شنبه",
        "Date": "1401/04/21",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "چهارشنبه",
        "Date": "1401/04/22",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "پنجشنبه",
        "Date": "1401/04/23",
        "DayStartTime": 0,
        "DayEndTime": 0,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "جمعه",
        "Date": "1401/04/24",
        "DayStartTime": 0,
        "DayEndTime": 0,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "شنبه",
        "Date": "1401/04/25",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "یکشنبه",
        "Date": "1401/04/26",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "دوشنبه",
        "Date": "1401/04/27",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "سه شنبه",
        "Date": "1401/04/28",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "چهارشنبه",
        "Date": "1401/04/29",
        "DayStartTime": 7,
        "DayEndTime": 16,
        "StartTime": 7,
        "EndTime": 16,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "پنجشنبه",
        "Date": "1401/04/30",
        "DayStartTime": 0,
        "DayEndTime": 0,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    },
    {
        "Day": "جمعه",
        "Date": "1401/04/31",
        "DayStartTime": 0,
        "DayEndTime": 0,
        "StartTime": 0,
        "EndTime": 0,
        "StartTime2": 0,
        "EndTime2": 0,
        "StartTime3": 0,
        "EndTime3": 0,
        "HourlyLeaveStartTime": 0,
        "HourlyLeaveEndTime": 0,
        "DailyLeave": false,
        "SickLeave": false,
        "MissionDay": false,
        "MissionHours": 0,
        "Absence": false
    }
]