export const DocumentData = [
    {
        "DocumentId": "d791176a-2c5a-431c-aabc-6310eeb52679",
        "DocumentCode": "32018",
        "DocumentTrackCode": "33311",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-10-12",
        "DocumentTypeName": "رسید متفرقه",
        "RefDocumentCode": "976",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "بابت رسید دستی انبار شماره 976 از سجاد محبی",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "73761ef1-f9a6-4f37-8b3e-2da488a6d2d8",
        "DocumentCode": "32017",
        "DocumentTrackCode": "33310",
        "DocumentBalance": "400,000",
        "DocumentInsertDate": "2022-09-31",
        "DocumentTypeName": "در جریان وصول چک دریافتی",
        "RefDocumentCode": "594",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت درجریان وصول قراردادن چک دریافتی از تست  100 با سریال 123000",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "1b0a18f0-0195-4e64-841c-de2743842a5b",
        "DocumentCode": "32016",
        "DocumentTrackCode": "33309",
        "DocumentBalance": "1,000,000,000",
        "DocumentInsertDate": "2022-09-12",
        "DocumentTypeName": "پاس چک پرداختی",
        "RefDocumentCode": "77",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت پاس چک پرداختی به شرکت آرانوش خاورمیانه با سریال 43101 و پشت نمره 77",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "3a46308a-649a-47ed-b4b7-a6a0bd3abfb1",
        "DocumentCode": "32015",
        "DocumentTrackCode": "33308",
        "DocumentBalance": "32,700,000",
        "DocumentInsertDate": "2022-10-25",
        "DocumentTypeName": "دریافت حواله بانکی",
        "RefDocumentCode": "9944",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت دریافت حواله بانکی از مدیر سیستم با شماره دریافت 9944",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "d4769a0e-7d03-4bde-bf00-c320e9e2273c",
        "DocumentCode": "32014",
        "DocumentTrackCode": "33307",
        "DocumentBalance": "1,255,600,000",
        "DocumentInsertDate": "2022-12-11",
        "DocumentTypeName": "پاس چک پرداختی",
        "RefDocumentCode": "83",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت پاس چک پرداختی به آمای جهان گستر  یکتا با سریال 653309 و پشت نمره 83",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "a1aededa-7cee-4d0a-9751-882dc3723a02",
        "DocumentCode": "32013",
        "DocumentTrackCode": "33306",
        "DocumentBalance": "14,000,000",
        "DocumentInsertDate": "2022-10-12",
        "DocumentTypeName": "دریافت حواله بانکی",
        "RefDocumentCode": "9941",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت دریافت حواله بانکی از حامد کرمی با شماره دریافت 9941",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "5bf66b31-97af-4ecb-8948-9773315e5b1c",
        "DocumentCode": "32012",
        "DocumentTrackCode": "33305",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-04-21",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1103",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "922d0eed-5737-4511-9620-7718ec755c81",
        "DocumentCode": "32011",
        "DocumentTrackCode": "33303",
        "DocumentBalance": "9,400,000",
        "DocumentInsertDate": "2022-12-10",
        "DocumentTypeName": "خرج چک مشتری",
        "RefDocumentCode": "86",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت خرج چک دریافتی از فروشگاه زنجیره ای رفاه 2 به شرکت آرانوش خاورمیانه با سریال 12123144455121",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "8bfeb40b-263a-4ab6-890f-83089c54feb7",
        "DocumentCode": "32010",
        "DocumentTrackCode": "33304",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-12-10",
        "DocumentTypeName": "عمومی",
        "RefDocumentCode": "",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "lkjj",
        "DocumentState": "غیر قطعی",
        "Attachments": "<a onclick=\"AttachmentClicked(this);return false;\"  href=\"../../../../../../Uploads/AccountingDocument/122-11-6-9-45-31-650/شرکت های زیرمجموعه بنیاد مستضعفان - 14010808.docx\" target=\"_blank\">شرکت های زیرمجموعه بنیاد مستضعفان - 14010808.docx</a>",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "50e9d212-b8eb-40a8-9e45-8bfe04db1885",
        "DocumentCode": "32009",
        "DocumentTrackCode": "33302",
        "DocumentBalance": "6,400,000",
        "DocumentInsertDate": "2022-10-25",
        "DocumentTypeName": "دریافت چک",
        "RefDocumentCode": "600",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت دریافت چک از عباس بابایی با سریال 564852",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "5117dba6-fdb2-4b75-8c95-5ac60a5bfc39",
        "DocumentCode": "32008",
        "DocumentTrackCode": "33301",
        "DocumentBalance": "10,144,662",
        "DocumentInsertDate": "2022-10-25",
        "DocumentTypeName": "دریافت حواله بانکی",
        "RefDocumentCode": "9943",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت دریافت حواله بانکی از سعید ویسی با شماره دریافت 9943",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "69cad18d-ea5e-4610-8f00-73f545c0f548",
        "DocumentCode": "32007",
        "DocumentTrackCode": "33300",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-21",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1102",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "05db2a19-62aa-4fe7-a16e-aeabf8ca6b11",
        "DocumentCode": "32006",
        "DocumentTrackCode": "33299",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-11-28",
        "DocumentTypeName": "شارژ بانک",
        "RefDocumentCode": "80",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت شارژ بانک سپه 10031177 توسط  بانک کشاورزی اول دوره",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "c757cc22-b605-44a9-a2c4-6eef9c682821",
        "DocumentCode": "32005",
        "DocumentTrackCode": "33298",
        "DocumentBalance": "11,463,684",
        "DocumentInsertDate": "2022-11-13",
        "DocumentTypeName": "رسید برگشت از توزیع",
        "RefDocumentCode": "986",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "بابت برگشت از توزیع کالا توسط مدیر سیستم طی رسید انبار شماره 986 شرح <توضیحات فروش> ورود به انبار <نام-انبار",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "96211e1a-e53b-424a-b9e1-9b108fcdc2cd",
        "DocumentCode": "32004",
        "DocumentTrackCode": "33297",
        "DocumentBalance": "17,987,220",
        "DocumentInsertDate": "2022-11-13",
        "DocumentTypeName": "فروش",
        "RefDocumentCode": "13023",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت فروش کالا به ادیب باقری طی شماره فاکتور 13023 پیش فاکتور 1014316 و حواله 1113 شرح تحویل روز شنبه",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "b641b6e4-0c0a-4330-aa66-d48d1e6f0a52",
        "DocumentCode": "32003",
        "DocumentTrackCode": "33296",
        "DocumentBalance": "19,457,292",
        "DocumentInsertDate": "2022-11-13",
        "DocumentTypeName": "حواله موزع",
        "RefDocumentCode": "1113",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "بابت تحویل امانی کالا به مدیر سیستم طی حواله انبار شماره 1113 شرح  ارسال به انبار انبار اصلی",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "fbc783e3-19b0-444e-8d94-2366a9ad892e",
        "DocumentCode": "32002",
        "DocumentTrackCode": "33295",
        "DocumentBalance": "64,680,000",
        "DocumentInsertDate": "2022-10-25",
        "DocumentTypeName": "خرید",
        "RefDocumentCode": "0139",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت خرید از شرکت  دماوند طی فاکتور شماره 0139 به شماره رسید انبار 982 شرح  ورود به انبار انبار اصلی",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "d03fb42b-9a91-4faf-ab7b-00485aa6cfa7",
        "DocumentCode": "32001",
        "DocumentTrackCode": "33294",
        "DocumentBalance": "309,552,462",
        "DocumentInsertDate": "2022-10-29",
        "DocumentTypeName": "فروش مستقیم",
        "RefDocumentCode": "13022",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت فروش کالا به مدیر سیستم طی شماره فاکتور 13022 پیش فاکتور 1014526 و حواله 1112 شرح  از حذف مدیر سیستم جدا خودداری کنید. (متن های پیش فرض را قبل از راه اندازی حذف کنید)",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "700f6214-3944-4422-8d37-463cf390e5d8",
        "DocumentCode": "32000",
        "DocumentTrackCode": "33293",
        "DocumentBalance": "1,000,000",
        "DocumentInsertDate": "2022-10-29",
        "DocumentTypeName": "کسری ریالی موزع",
        "RefDocumentCode": "903",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت مغایرت نقدی موزع(جهانگرد رضایی) در سرجمع شماره 903",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "70efc18a-6f92-47d1-a6e0-64462e476103",
        "DocumentCode": "31999",
        "DocumentTrackCode": "33292",
        "DocumentBalance": "4,000,000",
        "DocumentInsertDate": "2022-10-29",
        "DocumentTypeName": "شارژ بانک",
        "RefDocumentCode": "79",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت شارژ بانک سپه خورشید 6-1070-5892 توسط صندوق اصلی",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    }
]

export const TrashData = [
    {
        "DocumentId": "761a1663-aeb8-4ff9-9da5-fac05da35452",
        "DocumentTrackCode": "33219",
        "DocumentCode": "33219",
        "DocumentDescription": "ثبت بابت فروش کالا به مصیب جباری طی شماره فاکتور 12993 پیش فاکتور 1014406 و حواله 1033 شرح ",
        "DocumentInsertDate": "2022-09-21",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "فروش",
        "RefDocumentCode": "12993",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-21",
        "DocumentBalance": "4,359,462"
    },
    {
        "DocumentId": "028869a6-3c46-4106-9dc2-63a78e04b560",
        "DocumentTrackCode": "33192",
        "DocumentCode": "33192",
        "DocumentDescription": "ثبت بابت پرداخت چک به شرکت آرانوش خاورمیانه با سریال 43104 و پشت نمره 82 شرح ",
        "DocumentInsertDate": "2022-09-21",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "پرداخت چک",
        "RefDocumentCode": "82",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-21",
        "DocumentBalance": "1,000,000,000"
    },
    {
        "DocumentId": "4c3a8b10-1ce1-4716-8b1e-3231e3b3bb5f",
        "DocumentTrackCode": "33191",
        "DocumentCode": "33191",
        "DocumentDescription": "ثبت بابت پرداخت چک به شرکت آرانوش خاورمیانه با سریال 43103 و پشت نمره 81 شرح ",
        "DocumentInsertDate": "2022-09-21",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "پرداخت چک",
        "RefDocumentCode": "81",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-21",
        "DocumentBalance": "1,000,000,000"
    },
    {
        "DocumentId": "fb8f4b88-5ca6-4e6b-95d0-388be32bfac4",
        "DocumentTrackCode": "33190",
        "DocumentCode": "33190",
        "DocumentDescription": "ثبت بابت خرج چک دریافتی از کیوان حسینی به شرکت آرانوش خاورمیانه با سریال 21413213",
        "DocumentInsertDate": "2022-09-21",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "خرج چک مشتری",
        "RefDocumentCode": "80",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-21",
        "DocumentBalance": "1,000,000"
    },
    {
        "DocumentId": "914c8153-47da-4897-8498-7e01421e8e0f",
        "DocumentTrackCode": "33189",
        "DocumentCode": "33189",
        "DocumentDescription": "ثبت بابت پرداخت چک به شرکت آرانوش خاورمیانه با سریال 43103 و پشت نمره 79 شرح ",
        "DocumentInsertDate": "2022-09-21",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "پرداخت چک",
        "RefDocumentCode": "79",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-21",
        "DocumentBalance": "1,000,000"
    },
    {
        "DocumentId": "97868a4f-a400-4f80-b00b-96cce7258243",
        "DocumentTrackCode": "33188",
        "DocumentCode": "33188",
        "DocumentDescription": "ثبت بابت پرداخت چک به شرکت آرانوش خاورمیانه با سریال 43102 و پشت نمره 78 شرح ",
        "DocumentInsertDate": "2022-09-21",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "پرداخت چک",
        "RefDocumentCode": "78",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-21",
        "DocumentBalance": "1,000,000,000"
    },
    {
        "DocumentId": "206aaa9a-713e-4ff5-ac79-958feabd0500",
        "DocumentTrackCode": "33187",
        "DocumentCode": "33187",
        "DocumentDescription": "ثبت بابت پرداخت چک به شرکت آرانوش خاورمیانه با سریال 43101 و پشت نمره 77 شرح ",
        "DocumentInsertDate": "2022-09-21",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "پرداخت چک",
        "RefDocumentCode": "77",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-21",
        "DocumentBalance": "1,000,000,000"
    },
    {
        "DocumentId": "8b17e9e8-cdcb-4f7f-871a-7ded36e9fdf0",
        "DocumentTrackCode": "33186",
        "DocumentCode": "33186",
        "DocumentDescription": "ثبت بابت پرداخت چک به شرکت آرانوش خاورمیانه با سریال 43100 و پشت نمره 76 شرح ",
        "DocumentInsertDate": "2022-09-21",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "پرداخت چک",
        "RefDocumentCode": "76",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-21",
        "DocumentBalance": "1,000,000,000"
    },
    {
        "DocumentId": "6ed4a9d4-886c-401b-8664-4ff67ae924f0",
        "DocumentTrackCode": "33134",
        "DocumentCode": "33134",
        "DocumentDescription": "ثبت بابت فروش کالا به فروشکاه زنجیره ای  رفاه 1 طی شماره فاکتور 12953 پیش فاکتور 1014510 و حواله 1090 شرح ",
        "DocumentInsertDate": "2022-09-19",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "فروش مستقیم",
        "RefDocumentCode": "12953",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-19",
        "DocumentBalance": "12,000,000"
    },
    {
        "DocumentId": "b68c9852-34d5-401e-99b0-09caf9bac725",
        "DocumentTrackCode": "33132",
        "DocumentCode": "33132",
        "DocumentDescription": "بابت رسید دستی انبار شماره 945 از ",
        "DocumentInsertDate": "2022-09-19",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "رسید متفرقه",
        "RefDocumentCode": "945",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-19",
        "DocumentBalance": "6,000,000"
    },
    {
        "DocumentId": "bdcd4282-5ddc-4395-a9ab-e80049acdfb7",
        "DocumentTrackCode": "33129",
        "DocumentCode": "33129",
        "DocumentDescription": "ثبت بابت خرید از شرکت  سیمین سپهر سپاهان اصالت  طی فاکتور شماره 0126 به شماره رسید انبار 946 شرح  ورود به انبار انبار اصلی",
        "DocumentInsertDate": "2022-09-19",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "خرید",
        "RefDocumentCode": "0126",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-19",
        "DocumentBalance": "0"
    },
    {
        "DocumentId": "32ec8dc9-bc2b-4fb3-b232-e206ec5c02cd",
        "DocumentTrackCode": "33128",
        "DocumentCode": "33128",
        "DocumentDescription": "ثبت بابت دریافت چک از فروشکاه زنجیره ای  رفاه 1 با سریال 543333",
        "DocumentInsertDate": "2022-09-19",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "دریافت چک",
        "RefDocumentCode": "595",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-19",
        "DocumentBalance": "9,400,000"
    },
    {
        "DocumentId": "5c0191c4-21eb-49de-b7f6-3c4f03f85044",
        "DocumentTrackCode": "33124",
        "DocumentCode": "33124",
        "DocumentDescription": "ثبت بابت فروش کالا به فروشگاه زنجیره ای رفاه 2 طی شماره فاکتور 12951 پیش فاکتور 1014506 و حواله 1085 شرح ",
        "DocumentInsertDate": "2022-09-19",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "فروش",
        "RefDocumentCode": "12951",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-19",
        "DocumentBalance": "7,781,736"
    },
    {
        "DocumentId": "61e06bc1-1387-44b7-931a-ca286fd81658",
        "DocumentTrackCode": "33123",
        "DocumentCode": "33123",
        "DocumentDescription": "بابت تحویل امانی کالا به عبدل علی علوی پور طی حواله انبار شماره 1085 شرح  ارسال به انبار انبار اصلی",
        "DocumentInsertDate": "2022-09-19",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "عمومی",
        "RefDocumentCode": "",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-19",
        "DocumentBalance": "3,367,236"
    },
    {
        "DocumentId": "189a2481-2284-4490-b62d-6e2662409078",
        "DocumentTrackCode": "33102",
        "DocumentCode": "33102",
        "DocumentDescription": "ثبت بابت پرداخت وجه نقد به شرکت میهن با شماره پرداخت 1816",
        "DocumentInsertDate": "2022-09-05",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "پرداخت نقد",
        "RefDocumentCode": "1816",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-05",
        "DocumentBalance": "739,776,520"
    },
    {
        "DocumentId": "e11df3d3-fb5e-4b43-9488-b89afc84069f",
        "DocumentTrackCode": "33071",
        "DocumentCode": "33071",
        "DocumentDescription": "ثبت بابت فروش کالا به مشتری تست 3 طی شماره فاکتور 12923 پیش فاکتور 1014497 و حواله 1074 شرح ",
        "DocumentInsertDate": "2022-09-04",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "فروش",
        "RefDocumentCode": "12923",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-04",
        "DocumentBalance": "25,920,000"
    },
    {
        "DocumentId": "34820f72-6442-49b5-ac25-12cd717639a3",
        "DocumentTrackCode": "33070",
        "DocumentCode": "33070",
        "DocumentDescription": "ثبت بابت فروش کالا به مشتری  تست 2 طی شماره فاکتور 12922 پیش فاکتور 1014496 و حواله 1074 شرح ",
        "DocumentInsertDate": "2022-09-04",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "فروش",
        "RefDocumentCode": "12922",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-04",
        "DocumentBalance": "45,320,000"
    },
    {
        "DocumentId": "825c88b7-c6f0-4fdb-b755-56e9f13ab304",
        "DocumentTrackCode": "33069",
        "DocumentCode": "33069",
        "DocumentDescription": "ثبت بابت فروش کالا به مشتری  تست 1 طی شماره فاکتور 12921 پیش فاکتور 1014495 و حواله 1074 شرح ",
        "DocumentInsertDate": "2022-09-04",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "فروش",
        "RefDocumentCode": "12921",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-04",
        "DocumentBalance": "19,320,000"
    },
    {
        "DocumentId": "700700d8-6edb-4195-ad04-36f73bdb2530",
        "DocumentTrackCode": "33068",
        "DocumentCode": "33068",
        "DocumentDescription": "بابت تحویل امانی کالا به موزع تست 1 طی حواله انبار شماره 1074 شرح  ارسال به انبار انبار اصلی",
        "DocumentInsertDate": "2022-09-04",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "عمومی",
        "RefDocumentCode": "",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-04",
        "DocumentBalance": "45,280,000"
    },
    {
        "DocumentId": "f760057a-175b-4d7c-859a-fed404779579",
        "DocumentTrackCode": "33066",
        "DocumentCode": "33066",
        "DocumentDescription": "ثبت بابت خرید از تامین کننده تست طی فاکتور شماره 0122 به شماره رسید انبار 936 شرح خرید تستی  ورود به انبار انبار اصلی",
        "DocumentInsertDate": "2022-09-04",
        "DocumentInsertUser": "مدیر سیستم",
        "DocumentType": "خرید",
        "RefDocumentCode": "0122",
        "DocumentUpdateUser": "مدیر سیستم",
        "DocumentDeleteUser": "مدیر سیستم",
        "DocumentDeleteDate": "2022-09-04",
        "DocumentBalance": "0"
    }
]

export const ControlData = [
    {
        "DocumentId": "d791176a-2c5a-431c-aabc-6310eeb52679",
        "DocumentCode": "32018",
        "DocumentTrackCode": "33311",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-10-12",
        "DocumentTypeName": "رسید متفرقه",
        "RefDocumentCode": "976",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "بابت رسید دستی انبار شماره 976 از سجاد محبی",
        "DocumentState": "غیر قطعی",
        "Attachments": "<a onclick=\"AttachmentClicked(this);return false;\"  href=\"../../../../../../Uploads/AccountingDocument/d791176a-2c5a-431c-aabc-6310eeb52679-122-11-6-9-45-31-650/Checked.bmp\" target=\"_blank\">Checked.bmp</a><br/><a onclick=\"AttachmentClicked(this);return false;\"  href=\"../../../../../../Uploads/AccountingDocument/d791176a-2c5a-431c-aabc-6310eeb52679-122-11-6-9-45-31-650/تأیید کد پستی - 14010822.pdf\" target=\"_blank\">تأیید کد پستی - 14010822.pdf</a>",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "5bf66b31-97af-4ecb-8948-9773315e5b1c",
        "DocumentCode": "32012",
        "DocumentTrackCode": "33305",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-04-21",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1103",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "69cad18d-ea5e-4610-8f00-73f545c0f548",
        "DocumentCode": "32007",
        "DocumentTrackCode": "33300",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-21",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1102",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "05db2a19-62aa-4fe7-a16e-aeabf8ca6b11",
        "DocumentCode": "32006",
        "DocumentTrackCode": "33299",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-11-28",
        "DocumentTypeName": "شارژ بانک",
        "RefDocumentCode": "80",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت شارژ بانک سپه 10031177 توسط  بانک کشاورزی اول دوره",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "dec3ef72-1275-4771-8321-67162d5a65f2",
        "DocumentCode": "31932",
        "DocumentTrackCode": "33220",
        "DocumentBalance": "172,327",
        "DocumentInsertDate": "2022-09-21",
        "DocumentTypeName": "فروش مستقیم",
        "RefDocumentCode": "12994",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت فروش کالا به مصیب جباری طی شماره فاکتور 12994 پیش فاکتور 1014516 و حواله 1101 شرح ",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "7dbabaaa-3a57-4800-9a02-0cc368eeba6f",
        "DocumentCode": "31931",
        "DocumentTrackCode": "33199",
        "DocumentBalance": "456,800",
        "DocumentInsertDate": "2022-09-21",
        "DocumentTypeName": "شارژ بانک",
        "RefDocumentCode": "77",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت شارژ بانک سپه 10031177 توسط بانک سپه عابر بانک",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "be5d7d49-f0ff-4b71-a5dd-1a8b9aa05c2e",
        "DocumentCode": "31930",
        "DocumentTrackCode": "33198",
        "DocumentBalance": "2,130,000",
        "DocumentInsertDate": "2022-09-21",
        "DocumentTypeName": "شارژ صندوق",
        "RefDocumentCode": "4",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت شارژ صندوق اصلی توسط بانک کشاورزی 1 اول دوره",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "90d83884-ff46-4a98-a2f8-9e5af6fbba48",
        "DocumentCode": "31877",
        "DocumentTrackCode": "33167",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-20",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1097",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "45c393ee-29f3-4996-9a14-6af7c0ca70bf",
        "DocumentCode": "31876",
        "DocumentTrackCode": "33164",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-20",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1096",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "e944e95c-279f-42fc-a2e2-895e9f4c070c",
        "DocumentCode": "31875",
        "DocumentTrackCode": "33165",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-20",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1095",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "d2757429-5ba7-4596-9915-3cd3ffc6506f",
        "DocumentCode": "31874",
        "DocumentTrackCode": "33166",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-20",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1094",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "459cf8a7-3903-49ae-8a41-63713ee48a9c",
        "DocumentCode": "31873",
        "DocumentTrackCode": "33169",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-20",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1093",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "b6e3c08b-1637-4361-b80a-9b424c3292ae",
        "DocumentCode": "31871",
        "DocumentTrackCode": "33168",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-20",
        "DocumentTypeName": "حواله انبار به انبار",
        "RefDocumentCode": "1091",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "cd70d62b-d297-42ca-80d3-5d03570268e1",
        "DocumentCode": "31868",
        "DocumentTrackCode": "33171",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-20",
        "DocumentTypeName": "خرید",
        "RefDocumentCode": "0128",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت خرید از شرکت ژینا نوش روژهلات طی فاکتور شماره 0128 به شماره رسید انبار 960 شرح  ورود به انبار انبار گرمدره",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "df01f978-3678-479f-8d15-5916f7fdd35c",
        "DocumentCode": "31867",
        "DocumentTrackCode": "33163",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-09-20",
        "DocumentTypeName": "خرید",
        "RefDocumentCode": "0127",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت خرید از شرکت آرانوش خاورمیانه طی فاکتور شماره 0127 به شماره رسید انبار 959 شرح درج شده از طریق منوی نیازمندیهای خرید ورود به انبار انبار اصلی",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "cf3eb4fd-a185-4458-ad7b-16a4083009df",
        "DocumentCode": "31762",
        "DocumentTrackCode": "33042",
        "DocumentBalance": "100,000",
        "DocumentInsertDate": "2022-08-21",
        "DocumentTypeName": "عمومی",
        "RefDocumentCode": "",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "بابت",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "82d66499-dea3-413a-a0b7-49abe0ba0282",
        "DocumentCode": "31761",
        "DocumentTrackCode": "33040",
        "DocumentBalance": "759,120",
        "DocumentInsertDate": "2022-08-20",
        "DocumentTypeName": "حواله متفرقه",
        "RefDocumentCode": "1070",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "بابت حواله دستی انبار شماره 1070 به وام مضاربه ای بانک سپه",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "8bd5b969-9638-4f8b-9813-85f40b2e80a4",
        "DocumentCode": "31760",
        "DocumentTrackCode": "33039",
        "DocumentBalance": "100,000,000",
        "DocumentInsertDate": "2022-08-20",
        "DocumentTypeName": "رسید متفرقه",
        "RefDocumentCode": "930",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "بابت رسید دستی انبار شماره 930 از بانک سپه کارت خرید کالا",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "4ebdfe7c-4704-483b-b4a7-d92111e437ae",
        "DocumentCode": "31746",
        "DocumentTrackCode": "33045",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-08-20",
        "DocumentTypeName": "خرید",
        "RefDocumentCode": "0119",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت خرید از شرکت آرانوش خاورمیانه طی فاکتور شماره 0119 به شماره رسید انبار 932 شرح درج شده از طریق منوی نیازمندیهای خرید ورود به انبار انبار اصلی",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    },
    {
        "DocumentId": "e56e0f8a-e80a-41a3-a05a-acb4be39b906",
        "DocumentCode": "31733",
        "DocumentTrackCode": "33054",
        "DocumentBalance": "0",
        "DocumentInsertDate": "2022-08-15",
        "DocumentTypeName": "خرید",
        "RefDocumentCode": "0117",
        "InsertUser": "مدیر سیستم",
        "LastUpdateUser": "مدیر سیستم",
        "DocumentDescription": "ثبت بابت خرید از شرکت آرانوش خاورمیانه طی فاکتور شماره 0117 به شماره رسید انبار 935 شرح درج شده از طریق منوی نیازمندیهای خرید ورود به انبار انبار ایساکو",
        "DocumentState": "غیر قطعی",
        "Attachments": "",
        "HasAccountingMatch": false
    }
]