export const goodGiftDatagridLookup = [
    {
        Id: "1fd67148-60f5-4e02-ad8e-1dc6d29d7e20",
        Code: "30000018",
        Name: "پت هلو",
        Fee: "166666.666",
        CloseFee: "1000000",
        Count: "10",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 201,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false,
    },
];
export const cashDatagridCashLookup = [
    {
        Id: "6cde1a0a-9dac-4dc1-8a8e-016a120f5df4",
        Code: "30000001",
        Name: "صندوق اصلی",
        builderSeries: 5,
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 201,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false,
    },
    {
        Id: "bd506e3f-6975-45d0-8142-d1f113ca2005",
        Code: "30000004",
        Name: "صندوق دریافت چک ",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 201,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false,
    },
    {
        Id: "133269bb-40f8-4598-a66e-8a5afd10109f",
        Code: "30000005",
        Name: "صندوق تخفیفات ریالی",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 201,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false,
    },
    {
        Id: "f3a9da86-aed9-4329-89e8-e1436e3ca3e6",
        Code: "30000012",
        Name: "صندوق تنخواه روژین ویسی",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 201,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false,
    },
    {
        Id: "1fd67148-60f5-4e02-ad8e-1dc6d29d7e20",
        Code: "30000018",
        Name: "من",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 201,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false,
    },
];