const WareHouseNameData = [
    {
        Id: "31bdce8c-7bde-4887-bc51-ddc6c1824096",
        Code: "40000001",
        Name: "انبار اصلی",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 3,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    },
    {
        Id: "e9963115-5ab5-4ff2-8b56-1b1129cb3bc8",
        Code: "40000002",
        Name: "انبار ضایعات",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 3,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    },
    {
        Id: "6e6a892d-5bec-4fe0-bfd7-fcaf5be29693",
        Code: "40000003",
        Name: "انبار شمیران",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 3,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    },
    {
        Id: "0f3169c6-9d9d-43f8-afda-577b6e7bd921",
        Code: "40000004",
        Name: "انبار اهواز",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 3,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    },
    {
        Id: "886f09f4-9217-4585-871b-cc41c31c1cff",
        Code: "40000005",
        Name: "گیج",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 3,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    },
    {
        Id: "3dd751ad-3461-4dd8-851a-a9159a24a199",
        Code: "40000006",
        Name: "انبار ایساکو",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 3,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    },
    {
        Id: "9467ad09-0b2a-4067-9265-357ec6913fda",
        Code: "40000007",
        Name: "انبار متفرقه",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 3,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    },
    {
        Id: "1490135e-2da3-42e1-880e-645978d85bbb",
        Code: "40000008",
        Name: "انبار گرمدره",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 3,
        PartnerAddress: "",
        StuffGroupCode: "",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    }
]

const Warehouser = [
    {
        Id: "46011fee-e1ef-4df4-9d28-9b318b7209f2",
        Code: "20900002",
        Name: "حمید رضا پرویزی"
    }

]


export default {
    getWareHouseNameData() {
        return WareHouseNameData;
    },
    getWarehouserData() {
        return Warehouser;
    },
}
