const salaryData = [
    {
        Id: "03e53846-8454-41e9-b289-3245bf347be0",
        value: "30000011",
        Name: "صندوق سحر سیاه کمری ",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 203,
        PartnerAddress: "",
        Price: "21656565416",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    },
    {
        Id: "85ac5eee-043b-48f9-a182-785e8347f4fc",
        value: "30000014",
        Name: "تنخواه داودی",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 203,
        PartnerAddress: "",
        Price: "51614965156",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    },
    {
        Id: "6cf5e48d-d999-4b23-bd50-e008b7004c25",
        value: "30000016",
        Name: "تنخواه تست",
        PersonTelephone: "",
        PersonLegalName: "",
        DefaultPackageName: null,
        DefaultPackageId: "00000000-0000-0000-0000-000000000000",
        EntityGlobalType: 203,
        PartnerAddress: "",
        Price: "315418422",
        StuffBasketIds: [],
        Units: [],
        VATPercent: 0,
        SaleDefaultPackageId: null,
        SaleDefaultPackageUnitId: "",
        SaleDefaultPackageName: "",
        SaleDefaultPackageCoefficient: 0,
        BankAccountNumber: "",
        StuffDescription: "",
        MaxPackageCoefficient: 0,
        ExpirationDateFormat: null,
        EntityIsPerson: false
    }
]
export default {
    getSalaryData() {
        return salaryData;
    },
};