// assets
import GroupsOutlinedIcon from "@mui/icons-material/GroupsOutlined";
import EmojiEventsOutlinedIcon from "@mui/icons-material/EmojiEventsOutlined";
import {
  IconHomeDollar,
  IconSum,
  IconCashBanknote,
  IconFileDescription,
  IconCoin,
  IconBrandMastercard,
  IconRecharging,
  IconFileOff,
  IconFileDownload,
  IconFileUpload,
  IconFileZip,
  IconCashBanknoteOff,
  IconFileInvoice,
  IconFileCertificate,
} from "@tabler/icons";
// icons
const icons = {
  GroupsOutlinedIcon,
  EmojiEventsOutlinedIcon,
  IconHomeDollar,
  IconSum,
  IconCashBanknote,
  IconFileCertificate,
  IconFileDescription,
  IconCoin,
  IconBrandMastercard,
  IconRecharging,
  IconFileOff,
  IconFileDownload,
  IconFileUpload,
  IconFileZip,
  IconCashBanknoteOff,
  IconFileInvoice,
};
// ==============================|| MENU ITEMS - DASHBOARD ||============================== //
const FinancialTransaction = {
  id: "FinancialTransaction",
  title: "FinancialTransaction",
  type: "MegaGroup",
  breadcrumbs: true,
  icon: icons.IconHomeDollar,
  children: [
    {
      id: "PaymentDocument",
      title: "Payment Document",
      type: "SuperGroup",
      url: "/",
      icon: icons.IconFileUpload,
      breadcrumbs: true,
      children: [
        {
          id: "general",
          title: "General",
          type: "group",
          icon: icons.IconSum,
          children: [
            {
              id: "generalissuance",
              title: "Issuance",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/general/issuance",
              icon: icons.IconFileCertificate,
            },
            {
              id: "generaldisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/general/displayDetails",
              icon: icons.IconFileDescription,
            },
          ],
        },
        {
          id: "Cheque",
          title: "Cheque",
          type: "group",
          icon: icons.IconCashBanknote,
          children: [
            {
              id: "Chequeissuance",
              title: "Issuance",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/Cheque/issuance",
              icon: icons.IconFileCertificate,
            },
            {
              id: "ChequedisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/Cheque/displayDetails",
              icon: icons.IconFileDescription,
            },
          ],
        },
        {
          id: "cash",
          title: "Cash",
          type: "group",
          icon: icons.IconCoin,
          children: [
            {
              id: "cashissuance",
              title: "Issuance",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/Cash/issuance",
              icon: icons.IconFileCertificate,
            },
            {
              id: "cashdisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/Cash/display",
              icon: icons.IconFileDescription,
            },
          ],
        },
        {
          id: "RemittancePayable",
          title: "Remittance Payable",
          type: "group",
          icon: icons.IconBrandMastercard,
          breadcrumbs: true,
          children: [
            {
              id: "RemittancePayableissuance",
              title: "Issuance",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/RemittancePayable/issuance",
              icon: icons.IconFileCertificate,
              breadcrumbs: true,
            },
            {
              id: "RemittancePayabledisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/RemittancePayable/DisplayDetails",
              icon: icons.IconFileDescription,
            },
          ],
        },
        {
          id: "FundCharge",
          title: "Fund Charge",
          type: "group",
          icon: icons.IconRecharging,
          children: [
            {
              id: "FundChargeissuance",
              title: "Issuance",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/CashCharge/issuance",
              icon: icons.IconFileCertificate,
              breadcrumbs: true,
            },
            {
              id: "FundChargedisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/CashCharge/DisplayDetails",
              icon: icons.IconFileDescription,
            },
          ],
        },
        {
          id: "BankCharge",
          title: "Bank Charge",
          type: "group",
          icon: icons.IconRecharging,
          children: [
            {
              id: "BankChargeissuance",
              title: "Issuance",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/BankCharge/issuance",
              icon: icons.IconFileCertificate,
              breadcrumbs: true,
            },
            {
              id: "BankChargedisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/PaymentDocument/BankCharge/DisplayDetails",
              icon: icons.IconFileDescription,
            },
          ],
        },
        {
          id: "RevokeOfCheque",
          title: "Revoke of Cheque",
          type: "item",
          url: "/FinancialTransaction/PaymentDocument/ChequeCancelation",
          icon: icons.IconFileOff,
          breadcrumbs: true,
        },
      ],
    },
    {
      id: "receiptDocument",
      title: "Receipt Document",
      type: "SuperGroup",
      url: "/",
      icon: icons.IconFileDownload,
      breadcrumbs: true,
      children: [
        {
          id: "general",
          title: "General",
          type: "group",
          icon: icons.IconSum,
          children: [
            {
              id: "receiptDocumentissuance",
              title: "Issuance",
              type: "item",
              url: "/FinancialTransaction/receiptDocument/General/Issuance",
              icon: icons.IconFileCertificate,
              breadcrumbs: true,
            },
            {
              id: "receiptDocumentdisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/receiptDocument/General/DisplayDetails",
              icon: icons.IconFileDescription,
              breadcrumbs: true
            },
          ],
        },
        {
          id: "generalTotal",
          title: "General Total",
          type: "item",
          url: "/FinancialTransaction/receiptDocument/SaleTotalBatchReceipt/DisplayDetails",
          icon: icons.IconFileZip,
          breadcrumbs: true,
        },
        {
          id: "cheque",
          title: "Cheque",
          type: "group",
          icon: icons.IconCashBanknote,
          children: [
            {
              id: "generalTotalissuance",
              title: "Issuance",
              url: "/FinancialTransaction/receiptDocument/Cheque/Issuance",
              type: "item",
              icon: icons.IconFileCertificate,
              breadcrumbs: true,
            },
            {
              id: "generalTotaldisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/receiptDocument/Cheque/DisplayDetails",
              icon: icons.IconFileDescription,
              breadcrumbs: true,
            },
          ],
        },
        {
          id: "cash",
          title: "Cash",
          type: "group",
          icon: icons.IconCoin,
          children: [
            {
              id: "generalTotalcashissuance",
              title: "Issuance",
              type: "item",
              url: "/FinancialTransaction/receiptDocument/Cash/Issuance",
              icon: icons.IconFileCertificate,
            },
            {
              id: "generalTotalcashdisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/receiptDocument/Cash/DisplayDetails",
              icon: icons.IconFileDescription,
            },
          ],
        },
        {
          id: "remittanceReceivable",
          title: "Remittance Receivable",
          type: "group",
          icon: icons.IconBrandMastercard,
          children: [
            {
              id: "remittanceReceivableissuance",
              title: "Issuance",
              type: "item",
              url: "/FinancialTransaction/receiptDocument/remittanceReceivable/Issuance",
              breadcrumbs: true,
              icon: icons.IconFileCertificate,
            },
            {
              id: "remittanceReceivabledisplayDetails",
              title: "Display Details",
              type: "item",
              url: "/FinancialTransaction/receiptDocument/remittanceReceivable/displayDetails",
              icon: icons.IconFileDescription,
            }, 
          ],

        },
            ],
    },
    {
      id: "wastedSaleOrder",
      title: "Wasted Sale Order",
      type: "group",
      icon: icons.IconCashBanknote,
      children: [
        {
          id: "wastedSaleOrderdisplayDetails",
          title: "Display Details",
          type: "item",
          url: "/FinancialTransaction/wastedSaleOrder/DisplayDetails",
          icon: icons.IconFileDescription,
          breadcrumbs: true,
        },
        {
          id: "wastedSaleOrderissuance",
          title: "Issuance",
          url: "/FinancialTransaction/wastedSaleOrder/newWastedSaleOrder",
          type: "item",
          icon: icons.IconFileCertificate,
          breadcrumbs: true,
        },
      ],
    },
    {
      id: "wastedCheque",
      title: "Wasted Cheque",
      type: "group",
      icon: icons.IconCashBanknote,
      children: [
        {
          id: "wastedChequedisplayDetails",
          title: "Display Details",
          type: "item",
          url: "/FinancialTransaction/wastedCheque/DisplayDetails",
          icon: icons.IconFileDescription,
          breadcrumbs: true,
        },
        {
          id: "wastedChequeissuance",
          title: "Issuance",
          url: "/FinancialTransaction/wastedCheque/newWastedCheque",
          type: "item",
          icon: icons.IconFileCertificate,
          breadcrumbs: true,
        },
      ],
    },
    {
      id: "creditSummary",
      title: "Summary Of Salary",
      type: "item",
      url: "/FinancialTransaction/SummaryGrid",
      icon: icons.IconFileInvoice,
      breadcrumbs: true,
    },
  ],
};

export default FinancialTransaction;
