// assets

import {
    IconReportAnalytics,
    IconCalculator,
    IconFiles,
    IconBuilding,
    IconScale,
    IconCalendarStats,
    IconUserSearch,
    IconChartLine,
    IconFileChart,
    IconChartDots,
    IconHomeDollar,
    IconFileDownload,
    IconFileUpload,
    IconCashBanknote,
    IconFileDollar,
    IconChecklist,
    IconCashBanknoteOff,
    IconFileDescription,
    IconFileSpreadsheet,
    IconCheckupList,
    IconHome,
    IconFolders,
    IconClipboardList,
    IconFileSearch,
    IconExchange,
    IconShoppingCart,
    IconClipboardText,
    IconReportOff,
    IconTags,
    IconReportMoney,
    IconFileX,
    IconFileCheck,
    IconListNumbers,
    IconChartInfographic,
    IconRadar2,
    IconCash,
    IconMap,
    IconMessage2,
    IconFileInfo,
    IconUsers,
    IconUser,
    IconPackage,
    IconLockAccess,
    IconFileReport,
    IconFilesOff,
    IconFileTime
} from '@tabler/icons';
// icons
const icons = {
    IconFolders,
    IconClipboardList,
    IconFileSearch,
    IconExchange,
    IconShoppingCart,
    IconClipboardText,
    IconReportOff, IconTags,
    IconReportMoney,
    IconFileX,
    IconFileCheck,
    IconListNumbers,
    IconChartInfographic,
    IconRadar2,
    IconCash,
    IconMap,
    IconMessage2,
    IconFileInfo,
    IconUser,
    IconPackage,
    IconCalculator,
    IconLockAccess,
    IconFileReport,
    IconReportAnalytics,
    IconFiles,
    IconBuilding,
    IconScale,
    IconCalendarStats,
    IconUserSearch,
    IconChartLine,
    IconFileChart,
    IconChartDots,
    IconHomeDollar,
    IconFileDownload,
    IconFileUpload,
    IconCashBanknote,
    IconFileDollar,
    IconChecklist,
    IconCashBanknoteOff,
    IconFileDescription,
    IconFileSpreadsheet,
    IconCheckupList,
    IconHome,
    IconUsers,
    IconFilesOff,
    IconFileTime

};
// ==============================|| MENU ITEMS - DASHBOARD ||============================== //
const reports = {
    id: 'reports',
    title: 'Reports',
    type: 'MegaGroup',
    icon: icons.IconReportAnalytics,
    children: [
        {
            id: 'accounting',
            title: 'Accounting',
            type: 'SuperGroup',
            url: '/',
            icon: icons.IconCalculator,
            breadcrumbs: true,
            children: [
                {
                    id: 'reportDocuments',
                    title: 'Report Documents',
                    type: 'item',
                    url: '/Reports/Accounting/DocumentReports',
                    icon: icons.IconFiles,
                    breadcrumbs: true,
                }, {
                    id: 'officeReport',
                    title: 'Office Report',
                    type: 'item',
                    url: '/Reports/Accounting/officeReport',
                    icon: icons.IconBuilding,
                    breadcrumbs: true,
                }, {
                    id: 'TrialBalanceReports',
                    title: 'Trial Balance Report',
                    type: 'item',
                    url: '/Reports/Accounting/TrialBalanceReports',
                    icon: icons.IconScale,
                    breadcrumbs: true,
                }, {
                    id: 'accountNatureControlReport',
                    title: 'Account Nature Control Report',
                    type: 'group',
                    url: '/',
                    icon: icons.IconUserSearch,
                    breadcrumbs: true,
                    children: [
                        {
                            id: 'AccountsContraryToNature',
                            title: 'Accounts contrary to nature',
                            type: 'item',
                            url: '/Reports/Accounting/accountNatureControlReport/AccountsContraryToNature',
                            icon: icons.IconFilesOff,
                            breadcrumbs: true
                        },
                        {
                            id: 'ContraryNatureOfCourseDuration',
                            title: 'Contrary to the nature of the course duration',
                            type: 'item',
                            url: '/Reports/Accounting/accountNatureControlReport/ContraryNatureOfCourseDuration',
                            icon: icons.IconFileTime,
                            breadcrumbs: true
                        },
                    ]
                },
                {
                    id: 'profitAndLossReport',
                    title: 'Profit and Loss Report',
                    type: 'item',
                    url: '/Reports/Accounting/LostBenefit',
                    icon: icons.IconChartLine,
                    breadcrumbs: true,
                }, {
                    id: 'balanceSheetReport',
                    title: 'Balance Sheet Report',
                    type: 'item',
                    url: '/Reports/accounting/BalanceSheetReport',
                    icon: icons.IconReportAnalytics,
                    breadcrumbs: true,
                },
            ]
        },
        {
            id: 'financialTransaction',
            title: 'FinancialTransaction',
            type: 'group',
            url: '/',
            icon: icons.IconHomeDollar,
            breadcrumbs: true,
            children: [
                {
                    id: 'comprehensiveReportReception',
                    title: 'Comprehensive Report Reception',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileDownload,
                    breadcrumbs: true,
                }, {
                    id: 'comprehensiveReportPayment',
                    title: 'Comprehensive Report Payment',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileUpload,
                    breadcrumbs: true,
                }, {
                    id: 'comprehensiveReportOfReceivedCheque',
                    title: 'Comprehensive Report of Received Cheque',
                    type: 'item',
                    url: '/',
                    icon: icons.IconCashBanknote,
                    breadcrumbs: true,
                }, {
                    id: 'comprehensiveReportOfPayableCheque',
                    title: 'Comprehensive Report of Payable Cheque',
                    type: 'item',
                    url: '/',
                    icon: icons.IconCashBanknote,
                    breadcrumbs: true,
                }, {
                    id: 'detailedCashReport',
                    title: 'Detailed Cash Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileDollar,
                    breadcrumbs: true,
                }, {
                    id: 'detailedBankReport',
                    title: 'Detailed Bank Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileDollar,
                    breadcrumbs: true,
                }, {
                    id: 'factorReckoningReport',
                    title: 'Factor Reckoning Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconCashBanknoteOff,
                    breadcrumbs: true,
                }, {
                    id: 'factorAndWastedChequeReport',
                    title: 'Factor and Wasted Cheque Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileDescription,
                    breadcrumbs: true,
                }, {
                    id: 'cashingTheChequeReport',
                    title: 'Cashing the Cheque Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconCheckupList,
                    breadcrumbs: true,
                }, {
                    id: 'separableReckoningReport',
                    title: 'Separable Reckoning Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileSpreadsheet,
                    breadcrumbs: true,
                }
            ]
        },
        {
            id: 'wareHouse',
            title: 'WareHouse',
            type: 'group',
            icon: icons.IconHome,
            breadcrumbs: true,
            children: [
                {
                    id: 'inventoryReport',
                    title: 'Inventory Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconCheckupList,
                    breadcrumbs: true,
                }, {
                    id: 'cardexReport',
                    title: 'Cardex Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFolders,
                    breadcrumbs: true,
                }, {
                    id: 'receiptReport',
                    title: 'Receipt Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardList,
                    breadcrumbs: true,
                }, {
                    id: 'remittanceReport',
                    title: 'Remittance Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardList,
                    breadcrumbs: true,
                }, {
                    id: 'inventoryDiscrepancyReport',
                    title: 'Inventory Discrepancy Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileSearch,
                    breadcrumbs: true,
                }, {
                    id: 'stuffflowsReport',
                    title: 'Stuffflows Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconExchange,
                    breadcrumbs: true,
                },]
        },
        {
            id: 'purchase',
            title: 'Purchase',
            type: 'group',
            url: '/',
            icon: icons.IconShoppingCart,
            breadcrumbs: true,
            children: [
                {
                    id: 'orderReport',
                    title: 'Order Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'StuffsPurchaseReport',
                    title: 'Stuffs Purchase Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconCheckupList,
                    breadcrumbs: true,
                }, {
                    id: 'purchaseReportFromPartner',
                    title: 'Purchase Report from Partner',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'purchaseReversionsReport',
                    title: 'Purchase Reversions Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconReportOff,
                    breadcrumbs: true,
                }]
        },
        {
            id: 'sale',
            title: 'Sale',
            type: 'group',
            url: '/',
            icon: icons.IconTags,
            breadcrumbs: true,
            children: [
                {
                    id: 'factorReport',
                    title: 'Factor Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'stuffsSalesReport',
                    title: 'Stuffs Sales Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'separable Sales Report',
                    title: 'Separable Sales Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileSpreadsheet,
                    breadcrumbs: true,
                }, {
                    id: 'sellToPartnerReport',
                    title: 'Sell to Partner Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconReportMoney,
                    breadcrumbs: true,
                }, {
                    id: 'failedVisitReport',
                    title: 'Failed Visit Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconReportOff,
                    breadcrumbs: true,
                }, {
                    id: 'saleReversionReport',
                    title: 'Sale Reversion Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileX,
                    breadcrumbs: true,
                }, {
                    id: 'partitionReversionReport',
                    title: 'Partition Reversion Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileX,
                    breadcrumbs: true,
                }, {
                    id: 'visitorSaleReversionReport',
                    title: 'Visitor Sale Reversion Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileX,
                    breadcrumbs: true,
                }, {
                    id: 'visitorSalesReport',
                    title: 'Visitor Sales Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'headVisitorSalesReport',
                    title: 'Head Visitor Sales Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'payeesSaleReport',
                    title: 'Payees Sale Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'driverSaleReport',
                    title: 'Driver Sale Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'payeeReport',
                    title: 'Payee Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'freeProductSaleReport',
                    title: 'Free Product Sale Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'factorReckoningReport',
                    title: 'Factor Reckoning Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileCheck,
                    breadcrumbs: true,
                }, {
                    id: 'partnerAccountBook',
                    title: 'Partner Account Book',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'partnerSpecifics',
                    title: 'Partner Specifics',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'blackListCustomers',
                    title: 'Black List Customers',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardList,
                    breadcrumbs: true,
                }, {
                    id: 'visitList',
                    title: 'Visit List',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'stuffsListForSale',
                    title: 'Stuffs List for Sale',
                    type: 'item',
                    url: '/',
                    icon: icons.IconCheckupList,
                    breadcrumbs: true,
                }, {
                    id: 'goalSuccessReport',
                    title: 'Goal Success Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconChecklist,
                    breadcrumbs: true,
                }, {
                    id: 'goalCommissionReport',
                    title: 'Goal Commission Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileDollar,
                    breadcrumbs: true,
                }, {
                    id: 'visitPartnerReport',
                    title: 'Visit Partner Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileChart,
                    breadcrumbs: true,
                }, {
                    id: 'visitInformationReport',
                    title: 'Visit Information Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }, {
                    id: 'priceListReport',
                    title: 'Price List Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileDollar,
                    breadcrumbs: true,
                }, {
                    id: 'montlySaleReport',
                    title: 'Montly Sale Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileReport,
                    breadcrumbs: true,
                }, {
                    id: 'accountBallance_PartnerandPersonnelReport',
                    title: 'Account Ballance_Partnerand Personnel Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileReport,
                    breadcrumbs: true,
                }, {
                    id: 'saleOrderRemainPriceReport',
                    title: 'Sale Order Remain Price Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconFileSpreadsheet,
                    breadcrumbs: true,
                }, {
                    id: 'invoiceProductNumebrReport',
                    title: 'Invoice Product Numebr Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconListNumbers,
                    breadcrumbs: true,
                }, {
                    id: 'saleTimeComparingReport',
                    title: 'Sale Time Comparing Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconChartInfographic,
                    breadcrumbs: true,
                }, {
                    id: 'zoneVisitFrequencyReport',
                    title: 'Zone Visit Frequency Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconRadar2,
                    breadcrumbs: true,
                }]
        },
        {
            id: 'payroll',
            title: 'Payroll',
            type: 'group',
            url: '/',
            icon: icons.IconCash,
            breadcrumbs: true,
            children: [
                {
                    id: 'insuranceList',
                    title: 'Insurance List',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardList,
                    breadcrumbs: true,
                }, {
                    id: 'TaxList',
                    title: 'Tax List',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardList,
                    breadcrumbs: true,
                }]
        },
        {
            id: 'map',
            title: 'Map',
            type: 'group',
            url: '/',
            icon: icons.IconMap,
            breadcrumbs: true,
            children: [
                {
                    id: 'trackingReport',
                    title: 'Tracking Report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconRadar2,
                    breadcrumbs: true,
                }, {
                    id: 'partnersReport',
                    title: 'Partners report',
                    type: 'item',
                    url: '/',
                    icon: icons.IconClipboardText,
                    breadcrumbs: true,
                }]
        },
        {
            id: 'messageReport',
            title: 'Message Report',
            type: 'item',
            url: '/',
            icon: icons.IconMessage2,
            breadcrumbs: true
        },
        {
            id: 'baseInformation',
            title: 'Base Information',
            type: 'group',
            url: '/',
            icon: icons.IconFileInfo,
            breadcrumbs: true,
            children: [
                {
                    id: 'partner',
                    title: 'Partner',
                    type: 'item',
                    url: '/',
                    icon: icons.IconUsers,
                    breadcrumbs: true,
                }, {
                    id: 'personnel',
                    title: 'Personnel',
                    type: 'item',
                    url: '/',
                    icon: icons.IconUser,
                    breadcrumbs: true,
                }, {
                    id: 'stuffs',
                    title: 'Stuffs',
                    type: 'item',
                    url: '/',
                    icon: icons.IconPackage,
                    breadcrumbs: true,
                }, {
                    id: 'access',
                    title: 'Access',
                    type: 'item',
                    url: '/',
                    icon: icons.IconLockAccess,
                    breadcrumbs: true,
                }]
        },
    ]
};

export default reports;